import 'package:Autism/screens/cards/family_card/controller.dart';
import 'package:flutter/cupertino.dart';

class BodyController with ChangeNotifier {

  List<CardItem> bodyCardItem =[
    CardItem(id: 1, name: 'head', image: 'head0.png'),
    CardItem(id: 2, name: 'hair', image: 'hair.png'),
    CardItem(id: 3, name: 'eyebrow', image: 'eyebrow.png'),
    CardItem(id: 4, name: 'eye', image: 'eye.png'),
    CardItem(id: 5, name: 'nose', image: 'nose.png'),
    CardItem(id: 6, name: 'ear', image: 'ear.png'),
    CardItem(id: 7, name: 'tongue', image: 'tongue.png'),
    CardItem(id: 8, name: 'lips', image: 'lips.png'),
    CardItem(id: 9, name: 'teeth', image: 'teeth.png'),
    CardItem(id: 10, name: 'back', image: 'back.png'),
    CardItem(id: 11, name: 'shoulder', image: 'shoulder.png'),
    CardItem(id: 12, name: 'butt', image: 'butt.png'),
    CardItem(id: 13, name: 'chest', image: 'chest.png'),
    CardItem(id: 14, name: 'belly', image: 'belly.png'),
    CardItem(id: 15, name: 'hand elbow', image: 'hand elbow.png'),
    CardItem(id: 16, name: 'palm of hand', image: 'palm of hand.png'),
    CardItem(id: 17, name: 'finger', image: 'finger.png'),
    CardItem(id: 18, name: 'leg', image: 'leg.png'),
    CardItem(id: 19, name: 'foot elbow', image: 'foot elbow.png'),
    CardItem(id: 20, name: 'palm of foot', image: 'palm of foot.png'),
    CardItem(id: 21, name: 'foot', image: 'foot.png'),
  ];
  // List<String> cardsImage = [
  //   'head0.png',
  //   'hair.png',
  //   'eyebrow.png',
  //   'eye.png',
  //   'nose.png',
  //   'ear.png',
  //   'tongue.png',
  //   'lips.png',
  //   'teeth.png',
  //   'back.png',
  //   'shoulder.png',
  //   'butt.png',
  //   'chest.png',
  //   'belly.png',
  //   'hand elbow.png',
  //   'palm of hand.png',
  //   'finger.png',
  //   'leg.png',
  //   'foot elbow.png',
  //   'palm of foot.png',
  //   'foot.png',
  // ];
  // List<String> cardsName = [
  //   'head',
  //   'hair',
  //   'eyebrow',
  //   'eye',
  //   'nose',
  //   'ear',
  //   'tongue',
  //   'lips',
  //   'teeth',
  //   'back',
  //   'shoulder',
  //   'butt',
  //   'chest',
  //   'belly',
  //   'hand elbow',
  //   'palm of hand',
  //   'finger',
  //   'leg',
  //   'foot elbow',
  //   'palm of foot',
  //   'foot',
  // ];

}
