import 'package:Autism/screens/cards/family_card/controller.dart';
import 'package:flutter/cupertino.dart';

class AlphabetController with ChangeNotifier {

  List<CardItem> alphabetCardItems =[
    CardItem(id: 1 ,image:'alphabet.png',name: '' ),
    CardItem(id: 2 ,image:'Bb.png',name: '' ),
    CardItem(id: 3 ,image:'Cc.png',name: '' ),
    CardItem(id: 4 ,image:'Dd.png',name: '' ),
    CardItem(id: 5 ,image:'Ee.png',name: '' ),
    CardItem(id: 6 ,image:'Ff.png',name: '' ),
    CardItem(id: 7 ,image:'Gg.png',name: '' ),
    CardItem(id: 8 ,image:'Hh.png',name: '' ),
    CardItem(id: 9 ,image:'Ii.png',name: '' ),
    CardItem(id: 10 ,image:'Jj.png',name: '' ),
    CardItem(id: 11 ,image:'Kk.png',name: '' ),
    CardItem(id: 12 ,image:'Ll.png',name: '' ),
    CardItem(id: 13 ,image:'Mm.png',name: '' ),
    CardItem(id: 14 ,image:'Nn.png',name: '' ),
    CardItem(id: 15 ,image:'Oo.png',name: '' ),
    CardItem(id: 16 ,image:'Pp.png',name: '' ),
    CardItem(id: 17 ,image:'Qq.png',name: '' ),
    CardItem(id: 18 ,image:'Rr.png',name: '' ),
    CardItem(id: 19 ,image:'Ss.png',name: '' ),
    CardItem(id: 20 ,image:'Tt.png',name: '' ),
    CardItem(id: 21 ,image:'Uu.png',name: '' ),
    CardItem(id: 22 ,image:'Vv.png',name: '' ),
    CardItem(id: 23 ,image:'Ww.png',name: '' ),
    CardItem(id: 24 ,image:'Xx.png',name: '' ),
    CardItem(id: 25 ,image:'Yy.png',name: '' ),
    CardItem(id: 26 ,image:'Zz.png',name: '' ),
  ];

  List<String> cardsImage = [
    'alphabet.png',
    'Bb.png',
    'Cc.png',
    'Dd.png',
    'Ee.png',
    'Ff.png',
    'Gg.png',
    'Hh.png',
    'Ii.png',
    'Jj.png',
    'Kk.png',
    'Ll.png',
    'Mm.png',
    'Nn.png',
    'Oo.png',
    'Pp.png',
    'Qq.png',
    'Rr.png',
    'Ss.png',
    'Tt.png',
    'Uu.png',
    'Vv.png',
    'Ww.png',
    'Xx.png',
    'Yy.png',
    'Zz.png',
  ];
  List<String> cardsName = [
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',

  ];

}


